Este livro tem como objetivo desenvolver no leitor um pensamento crítico e reflexivo sobre a ciência e seus métodos.
Para isso, realizou-se um importante esforço na busca de referências históricas que exemplificassem esta crítica ao conceito tradicional de ciência focado em um único modelo metodológico.
Este livro quer mostrar que esta concepção tradicional de ciência está fortemente ``amarrada'' a problemas e situações históricas passadas.
Como a ciência se constrói com base em problemas que mudam ao longo do tempo, esta visão de ciência deve ser superada.

No capítulo 1, é introduzido o conceito de ciência e suas transformações históricas.
E é a partir da visão histórica da ciência segundo Tomas S. Kuhn que este livro adquire sua força e orientação.
Pois é em textos que enfatizam as contradições ou reivindicam as mudanças no pensamento científico que o livro se baseia.
Para isso, foi necessário ir às fontes, tentar compreender o que Galileu Galileu viveu tal como relata Alexandre Koyré em seus ensaios.

No capítulo 2, são indicados três grandes linhas metodológicas que a ciência tem sofrido até agora: a escolástica, a empírica e a sistêmica.
A ideia é resgatar as fontes do pensamento científico que mostram as mudanças de racionalidade.
Neste sentido, exemplifica-se a racionalidade empirista no método de F. W. Taylor assim como a racionalidade sistêmica apresentada por L. v. Bertalanffy.
Mas para falar de empirismo surge a necessidade e a enorme dificuldade de falar sobre a escolástica.
É difícil falar sobre a escolástica pois é necessária uma formação filosófica e histórica profunda.
E falar sobre a escolástica nos leva ao intenso mundo filosófico dos gregos na antiguidade.

Este livro carece de aspectos práticos sobre o trabalho do pesquisador nos dias de hoje, contudo, o começo desta perspectiva foi iniciada no terceiro e último capítulo do livro.

O autor do livro está torcendo para que este seja um grande começo.
Um começo para o crescimento na formação científica, interpretativa e reflexiva dos leitores.
Naturalmente, o autor também estará envolvido profundamente neste crescimento.
Mas também é um começo para o aprofundamento de cada assunto desenvolvido em cada capítulo.

Para ter maiores detalhes sobre cada assunto abordado neste livro, recomendada-se a leitura dos textos indicados nas referências bibliográficas.
Em particular, você poderá constatar como é estimulante conhecer a vida e obra de Galileu Galilei por meio dos ensaios de Alexandre Koyré.
É a partir destas leituras que o estudo dos métodos da ciência, de uma perspectiva histórica e filosófica, se tornam atrativos e transformadores.

=== Público alvo

O público alvo desse livro são os alunos de Licenciatura em Computação, na
modalidade à distância footnote::[Embora ele tenha sido feito para atender aos alunos
da Universidade Federal da Paraíba, o seu uso não se restringe a esta 
universidade, podendo ser adotado por outras universidades do sistema UAB.].
Ele foi concebido para ser utilizado numa disciplina de _{disciplina}_,
no segundo semestre do curso.

[[como_estudar]]
=== Como você deve estudar cada capítulo

* Leia a visão geral do capítulo
* Estude os conteúdos das seções
* Realize as atividades no final do capítulo
* Verifique se você atingiu os objetivos do capítulo

.Na sala de aula do curso
* Tire dúvidas e discuta sobre as atividades do livro com outros integrantes do curso
* Leia materiais complementares eventualmente disponibilizados
* Realize as atividades propostas pelo professor da disciplina

////
Sempre terminar o arquivo com uma nova linha.
////

